version: '3'
services:
  app:
    image: 'users-api:latest'
    build: ./
    container_name: app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - postgresqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:${POSTGRES_PORT}/postgres
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgresqldb:
    image: 'postgres'
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    container_name: postgresqldb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}